### ISSUE TITLE
geom_table_npc() with ggplot() + facet_grid() not working

### ISSUE THREAD

**Issue by grt9** [aphalo/ggpp#16]
Hi @aphalo ,

I am trying to put a separate table per facet of a ggplot but can't get it working
I've tried following these links so far
https://docs.r4photobiology.info/ggpp/reference/geom_table.html#ref-examples
https://stackoverflow.com/questions/64811173/is-it-possible-to-use-geom-table-along-facet-grid
https://stackoverflow.com/questions/25554548/adding-sub-tables-on-each-panel-of-a-facet-ggplot-in-r?

1 - Extract required data from huge DF
```
mydata <-
  RIII_ALLDATA_DonorAveraged_long %>%
  dplyr::filter(!Compound1Concentration > 100) %>% 
  dplyr::filter(!marker %in% c("CD25", "CD137", "CD19", "CD107a")) %>% 
  dplyr::filter(statType == "Count") %>% 
  dplyr::filter(CellPop %in% c("AllCD3+ AllCD4+",
                               "AllCD3+ AllCD8+",
                               "AllCD3+ CD4+CD8+"))
  dplyr::filter(Labels %in% c("no drug control",
                              "Treatment 1",
                              "Treatment 2",
                              "Treatment 3",
                              "Treatment 4")) %>%
  dplyr::mutate(Labels = fct_recode(Labels,
                                    NDC = "no drug control"))
```

2 - Set up the plot 
```
gg <- 
  ggplot(mydata,
         aes(x = Compound1Concentration,
             y = value,
             fill = CellPop)) + 
  geom_bar(position = "stack", stat = "identity", color = "black") +
  facet_grid(CellLine ~ Labels, scales = "free_x", space = "free") + 
  scale_fill_nejm() + 
  x.axis.DRClow + 
  # scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  labs(x = "Treatment (pM)") 
```

3 - now try to put a table of values below each facet of the plot

```
tb <- mydata

# split big df of all data into list of separate dfs by cell line
tbs <- split(tb, tb$CellLine)

# make a new nested dataframe including faceting variable, x and y coordinates for table, and list of tables
dfnpc <- tibble(x = rep(0.5, length(tbs)),
                y = rep(0.5, length(tbs)),
                CellLine = levels(tb$CellLine),
                tbl = tbs)


gg + geom_table_npc(data = dfnpc,
                    aes(npcx = x,
                        npcy = y,
                        label = tbl))

```

The plot works independently of the geom table bit. When I try the `gg + geom_table_npc(...)` R just hangs
Please help!

**Comment by aphalo** [comment]
@grt9 I cannot run this code without data. 

I see in code chunk  1. a missing `%>%` at end of the 8th line.
In chunk 2. You need to include `Labels` in addition to `CellLine` in `dfnpc`, as both variables apear in `facet_grid()`.

Lacking the data I cannot test these fixes, but I think the problem is in your code, rather than in the package. If these suggestions do not solve the problem, please, create a reprex. If you've never heard of a reprex before, start by reading <https://www.tidyverse.org/help/#reprex>, and follow the advice further down the page. Do NOT include session info unless it's explicitly asked for, or you've used `reprex::reprex(..., si = TRUE)` to hide it away.

**Comment by grt9** [comment]
@aphalo thanks for the super quick reply

I had to cut a few bits for simplicity and not to share sensitive data (eg treatment names), so the missing `%>%` isn't a problem in the full code (`gg` runs fine), but thanks for catching it here. I indeed tried reprex but this is a very long script with sensitive data I can't share, and only selecting this part of the code just results in errors that objects can't be found, eg the starting df for `mydata`


I did indeed try to include both of the faceting variables in `dfnpc` but can't due to the layout of the data
```
> dfnpc <- tibble(x = rep(0.5, length(tbs)),
+                 y = rep(0.5, length(tbs)),
+                 CellLine = levels(tb$CellLine),
+                 Labels = levels(tb$Labels),
+                 tbl = tbs)
Error:
! Tibble columns must have compatible sizes.
• Size 43: Existing data.
• Size 13: Column `Labels`.
ℹ Only values of size one are recycled.
Run `rlang::last_error()` to see where the error occurred.
```

The plot I've created is a faceted, stacked histogram. I'd like a table of values under each facet, so a table of 3 rows x 6 columns

After going through a lot of options, I've settled on using `geom_text` with `position_nudge_to` to make a pseudo-table under each facet

```
mydata_long %>% 
  dplyr::filter(str_detect(name, pattern = "Count$")) %>% 
  ggplot(aes(x = Compound1Concentration,
             y = value,
             fill = CellPop)) + 
  geom_bar(position = "stack",
           stat = "identity",
           color = "black") +
  geom_text(data = mydata_long %>% dplyr::filter(str_detect(name, pattern = "Count_change$")),
    aes(label = paste0(round(value, 2), "%"),
        color = CellPop),
    position = position_nudge_to(y = c(-30000,-10000, -20000)),
    size = 2.5,
    fontface = "bold") +
  geom_hline(yintercept = 0) +
  facet_grid(CellLine ~ Labels, scales = "free_x", space = "free_x") + 
  scale_fill_nejm() +
  scale_color_nejm()
```

thanks for helping anyway!

**Comment by aphalo** [comment]
@grt9 Hi. A reprex is in most cases not based on the data set you are having trouble with. You can assemble some artificial data or use example data from the R distribution, 'ggpp' or some other package. Preferably, simpler data than your own, just the minimum needed to reproduce the problem. The code in the reprex should not include anything irrelevant to the problem you are reporting. In many cases, doing this already reveals what the problem is, either in user's code or in the package code. 

It is for sure that if a variable you are using for faceting is missing from the data, faceting will not work. Use `head()` or `print()` to print  the data and check whether all the columns/variables that are being referenced in `aes()` or facets are present. Remove from your plot all other statements that create plot layers, and see if the problem persists. With a reprex I could debug the code. I cannot help you simply by reading part of your code.

What versions of 'ggpp', 'ggplot2' and R are you using?
